{
  "account": "rab.le.dr.numerique",
  "userAgent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36",
  "cookies": [
    {
        "domain": ".www.tiktok.com",
        "expirationDate": 1774527721,
        "hostOnly": false,
        "httpOnly": false,
        "name": "delay_guest_mode_vid",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "8"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1783549538,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_R5EYE54KWQ",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1748989538.2.0.1748989538.0.0.542971702"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1784915274,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_C97F14JC77U63IDI7U40",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1751219274009::02zbw0-lQoJAC51NsIpP.4.1751219274232"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1785523562,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_ER02CH5NW5",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS1.1.1750963269.1.1.1750963562.0.0.1762660221"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782498782,
        "hostOnly": false,
        "httpOnly": true,
        "name": "tta_attr_id",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0.1750962783.7520327787631329281"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1787142049,
        "hostOnly": false,
        "httpOnly": true,
        "name": "tt-target-idc-sign",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fDwL6kF4ntKR97R30xnVKHjoC3srh1lqBeQ5P-i5x6Ea2EziF6Rtl4s03RzMM0XDGqnksu16Q3u8YcEF9KMB8BkBhVoctQSmRAQv8njp8HvTALYX6SyeFtw0E4WVaJZYHajbAvot8gCuurVbqZiLNEswU7yQpfZmqfXzDcnfpf8HvCHFp0wIOg8GXCXWSZNAceX5j_s0jSed3pbCUNAM2BhMef47eeu78MkQ-9RLgffh0v78g2GevIxDglnET5BpUS3Gw4StIAcnwVuh34YuvcuXjjsqzjzhZ_9tdPsV-Kt5PpXG-6xBSjjfhXfiZg4dYUSRpTvcTvx2eC4K8YcPoRS7vZwo1QvgSq5C55gxUziScmNcbW2wuFHHSbmsk1gHabQtdhGFH0DJZWzc2EyPmVrQqoNYkZZ5ImNWrwvYDHYM95HCVy_P9XZ-2RchXdzUY5gzXWcTzlgVcNwcJZsCR2RzLnOsAv5RUle7R1r27cY1ilmVvb4Rfr28k3PW6cmn"
    },
    {
        "domain": "www.tiktok.com",
        "hostOnly": true,
        "httpOnly": false,
        "name": "csrf_session_id",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "2fe14eac7d96840a6a14b1039a04ef12"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1785780044,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GA1.1.440448732.1748984172"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_C97F83JC77UC6ALACM60",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174713::khrzWb2cZPEwr7dlQmD5.1.1748985385151"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756508054.985026,
        "hostOnly": false,
        "httpOnly": false,
        "name": "msToken",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "oZVFnOCIkhdZbscQJGH6XdnttvZmc-16l6bWERRcE8IFb7TrFNsk9EOvkLpw2yLwXEr6zUuj5CeoX3RYlhYmh-5uovLCdMHLanBzpMVsUpEJpCXhzyZ5LsiegBfgRUoYdseOnFy59lUH6fQKRUJtfhI="
    },
    {
        "domain": ".www.tiktok.com",
        "expirationDate": 1755875484,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_tea_utm_cache_345918",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "{%22utm_source%22:%22whatsapp%22%2C%22utm_medium%22:%22android%22%2C%22utm_campaign%22:%22client_share%22}"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756760169,
        "hostOnly": false,
        "httpOnly": false,
        "name": "FPGCLGS",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2.1.k1$i1748984170$u261233179"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782066026,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sid_guard",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "9b40dbc54b7348dc49a977db2461ece0%7C1750962026%7C15551985%7CTue%2C+23-Dec-2025+18%3A20%3A11+GMT"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1787180054.103554,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ttwid",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1%7CnzsfXDeqYGCh-WpoSKFMmX7Ds9bKPrHamDVMo50EGPE%7C1755644054%7C1ed885201955daa5ab8635d6a39bfdda344ffc69b68cdf25e5ee9ed358d61e09"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756760179,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_gs",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "2.1.k1$i1748984170$u261233179"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_C97F65JC77UB71TGK1OG",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174711::JmdIMeNWO7MWXPQHlJZv.1.1748985385149"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1784915274,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1751219274011::lceOYl7nwcNDEn7xzyyO.4.1751219274011"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011.627932,
        "hostOnly": false,
        "httpOnly": true,
        "name": "store-country-code-src",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "uid"
    },
    {
        "domain": ".www.tiktok.com",
        "expirationDate": 1756233903,
        "hostOnly": false,
        "httpOnly": false,
        "name": "perf_feed_cache",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "{%22expireTimestamp%22:1756231200000%2C%22itemIds%22:[%227539268402989387030%22%2C%227534847272752893206%22%2C%227538156767004347670%22]}"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756760310,
        "hostOnly": false,
        "httpOnly": false,
        "name": "from_way",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "paid"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1784656694,
        "hostOnly": false,
        "httpOnly": false,
        "name": "cookie-consent",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "{%22optional%22:true%2C%22ga%22:true%2C%22af%22:true%2C%22fbp%22:true%2C%22lip%22:true%2C%22bing%22:true%2C%22ttads%22:true%2C%22reddit%22:true%2C%22hubspot%22:true%2C%22version%22:%22v10%22}"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "uid_tt",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "88a75a6116bec2ab92f8b807077ee8885341b5f9bab56cf87000fc09c94a8d80"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1785780050,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_HV1FL86553",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS2.1.s1751219271$o4$g1$t1751220050$j0$l0$h221166977"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1760789978,
        "hostOnly": false,
        "httpOnly": false,
        "name": "passport_csrf_token_default",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "c240d95281124fd0efe94555deb2cefb"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011.627705,
        "hostOnly": false,
        "httpOnly": true,
        "name": "store-country-sign",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "MEIEDDOHTrNbnV8zTYEDMwQgfGN-XmBiRPYWvqh6HhZeyRfJLFZRlfVoIHlcREFmLMkEEGSbYEKD-WCDrMkTBaa0grQ"
    },
    {
        "domain": "www.tiktok.com",
        "expirationDate": 1763420058,
        "hostOnly": true,
        "httpOnly": false,
        "name": "msToken",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "OGG5zHCNGrftPh8xLuPX-M64muP0ZMt8E4_45UcAQzV93L7q8s5ZpYW1w3prke_6D1Ph4PM5RaKVeFkuSXL9wtWLiIWOzNVpdnIo88r63zNywc8q46QgY5n9-aBxTGLUgsw1bPD36HcZwg=="
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782498130,
        "hostOnly": false,
        "httpOnly": true,
        "name": "d_ticket_ads",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "6640731072eaf346b03538f2ba1db30c6f207"
    },
    {
        "domain": ".tiktok.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "s_v_web_id",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "verify_meiigy4i_YM1vuvAw_FmKy_4hFF_ATNe_4E8ETAYTD31W"
    },
    {
        "domain": "www.tiktok.com",
        "expirationDate": 1787142017,
        "hostOnly": true,
        "httpOnly": false,
        "name": "pre_country",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "US"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011.627592,
        "hostOnly": false,
        "httpOnly": true,
        "name": "store-idc",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "no1a"
    },
    {
        "domain": "www.tiktok.com",
        "expirationDate": 1787142017,
        "hostOnly": true,
        "httpOnly": false,
        "name": "lang_type",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "en"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1758737253,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_fbp",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "fb.1.1748984173048.2046097132"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "ssid_ucp_v1",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1.0.0-KDhkMzNkOGFmZmE3ZDE2OTA0ZDc0NDVmMDFlM2U4ODQzZDRiMTJmY2QKGgihiMeMq4jJq2gQ6p72wgYYsws4AUDqB0gEEAUaBG5vMWEiIDliNDBkYmM1NGI3MzQ4ZGM0OWE5NzdkYjI0NjFlY2Uw"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_C97F9QBC77U37LFVJTOG",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174715::T-PyWaEws0JGGIY4b3sX.1.1748985385153"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756760318,
        "hostOnly": false,
        "httpOnly": true,
        "name": "_gtmeec",
        "path": "/",
        "sameSite": "strict",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "e30%3D"
    },
    {
        "domain": ".www.tiktok.com",
        "expirationDate": 1781564052,
        "hostOnly": false,
        "httpOnly": false,
        "name": "tiktok_webapp_theme",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "dark"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1785780050,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ga_Y2RSHPPW88",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GS2.1.s1751219272$o4$g1$t1751220050$j0$l0$h226875640"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756760179,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_gcl_aw",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "GCL.1748984179.Cj0KCQjwuvrBBhDcARIsAKRrkjdT41PUHespOt6K45ymBQ2rCC0Gp88FfgQjH4QFI7KO0uo9HTEYYJQaAr44EALw_wcB"
    },
    {
        "domain": ".www.tiktok.com",
        "expirationDate": 1755875481,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_tea_utm_cache_1988",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "{%22utm_source%22:%22whatsapp%22%2C%22utm_medium%22:%22android%22%2C%22utm_campaign%22:%22client_share%22}"
    },
    {
        "domain": ".www.tiktok.com",
        "expirationDate": 1755875481,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_tea_utm_cache_594856",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "{%22utm_source%22:%22whatsapp%22%2C%22utm_medium%22:%22android%22%2C%22utm_campaign%22:%22client_share%22}"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1784915274,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_tt_enable_cookie",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1788980107,
        "hostOnly": false,
        "httpOnly": false,
        "name": "_ttp",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2z5zqWi41rN9pUawQflNQSClcq9.tt.1"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756146010,
        "hostOnly": false,
        "httpOnly": true,
        "name": "cmpl_token",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "AgQQAPObF-RO0rhpyuU5ox0Y_Evo3SdZ_4QQYN7SGA"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782498010,
        "hostOnly": false,
        "httpOnly": true,
        "name": "d_ticket",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "90a410a83211ce0a95806b875ff741496f207"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756760172,
        "hostOnly": false,
        "httpOnly": false,
        "name": "FPAU",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1.2.1433508783.1748984173"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756760179,
        "hostOnly": false,
        "httpOnly": false,
        "name": "FPGCLAW",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "2.1.kCj0KCQjwuvrBBhDcARIsAKRrkjdT41PUHespOt6K45ymBQ2rCC0Gp88FfgQjH4QFI7KO0uo9HTEYYJQaAr44EALw_wcB$i1748984180"
    },
    {
        "domain": "www.tiktok.com",
        "expirationDate": 1758738010,
        "hostOnly": true,
        "httpOnly": false,
        "name": "last_login_method",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "email"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1756146010,
        "hostOnly": false,
        "httpOnly": true,
        "name": "multi_sids",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "7518517971783894049%3A9b40dbc54b7348dc49a977db2461ece0"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1787142045,
        "hostOnly": false,
        "httpOnly": true,
        "name": "odin_tt",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "f7bd8a68c17cbabf8b229eee571f2a23c2c5d337a689e18c1a3e6efb59810862c571bd5a67241d19d0cbbfda478d9da97571b7feed0f4c62a500dcf26026bbb39d4827e03b3a5ec82fc2e62d3267f98b"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1760789978,
        "hostOnly": false,
        "httpOnly": false,
        "name": "passport_csrf_token",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "c240d95281124fd0efe94555deb2cefb"
    },
    {
        "domain": ".www.tiktok.com",
        "hostOnly": false,
        "httpOnly": false,
        "name": "passport_fe_beating_status",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": true,
        "storeId": null,
        "value": "true"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sessionid",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "9b40dbc54b7348dc49a977db2461ece0"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sessionid_ss",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "9b40dbc54b7348dc49a977db2461ece0"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782324209,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sid_guard_ads",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "9669e20d5ad5f3204e6116aa2ed8cb59%7C1751220209%7C259200%7CWed%2C+02-Jul-2025+18%3A03%3A29+GMT"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sid_tt",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "9b40dbc54b7348dc49a977db2461ece0"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "sid_ucp_v1",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "1.0.0-KDhkMzNkOGFmZmE3ZDE2OTA0ZDc0NDVmMDFlM2U4ODQzZDRiMTJmY2QKGgihiMeMq4jJq2gQ6p72wgYYsws4AUDqB0gEEAUaBG5vMWEiIDliNDBkYmM1NGI3MzQ4ZGM0OWE5NzdkYjI0NjFlY2Uw"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011.627859,
        "hostOnly": false,
        "httpOnly": true,
        "name": "store-country-code",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "fr"
    },
    {
        "domain": ".www.tiktok.com",
        "expirationDate": 1781564052,
        "hostOnly": false,
        "httpOnly": false,
        "name": "tiktok_webapp_theme_source",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "auto"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011.627973,
        "hostOnly": false,
        "httpOnly": true,
        "name": "tt-target-idc",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "eu-ttp2"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1771196052.118887,
        "hostOnly": false,
        "httpOnly": true,
        "name": "tt_chain_token",
        "path": "/",
        "sameSite": null,
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "QyV08sHHXUJvrlgk6hRWNg=="
    },
    {
        "domain": ".tiktok.com",
        "hostOnly": false,
        "httpOnly": true,
        "name": "tt_csrf_token",
        "path": "/",
        "sameSite": "lax",
        "secure": true,
        "session": true,
        "storeId": null,
        "value": "P9ZIXbZ5-rsPXrhWlMIcQfc3pzafAnUTrbUo"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1780520152,
        "hostOnly": false,
        "httpOnly": false,
        "name": "tta_attr_id_mirror",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "0.1748984154.7511829741742063634"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_C97F413C77U6S6FS3KBG",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174707::73Fx81QumirH-aXpvYYp.1.1748985385142"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_CBUS2N3C77UB6N0891N0",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174718::paGZEHisYXlu27dyhc7u.1.1748985385162"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_CDICPPBC77UFUTJBVLI0",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174719::IRgfT-ObY-8orNmXtflc.1.1748985385164"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_CGCP5PJC77U5LCHF3VG0",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174725::QDCk3zazI05_5Y2b20HR.1.1748985385167"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1782681385,
        "hostOnly": false,
        "httpOnly": false,
        "name": "ttcsid_CS7J93RC77U6TI82IEB0",
        "path": "/",
        "sameSite": null,
        "secure": false,
        "session": false,
        "storeId": null,
        "value": "1748984174730::FcfeJT5eTGf_0SooZvF7.1.1748985385170"
    },
    {
        "domain": ".tiktok.com",
        "expirationDate": 1766514011,
        "hostOnly": false,
        "httpOnly": true,
        "name": "uid_tt_ss",
        "path": "/",
        "sameSite": "no_restriction",
        "secure": true,
        "session": false,
        "storeId": null,
        "value": "88a75a6116bec2ab92f8b807077ee8885341b5f9bab56cf87000fc09c94a8d80"
    }
]
}

